import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  containerTop: {
    flex: 1,
    flexDirection: 'row',
    paddingTop: 8,
    backgroundColor: '#102F74D0',
    alignItems: 'flex-start',
    height: '10%',
    paddingRight: 15,
  },
  searchStyle: {
    flex: 1,
    flexDirection: 'row',
    width: '100%',
    backgroundColor: null,
    elevation: null,
    borderBottomColor: 'white',
    borderBottomWidth: 1,
  },
  bkgDivUp: {
    width: '100%',
    height: '34%',
    backgroundColor: '#939EB6CE',
  },
  bkgDivDown: {
    width: '100%',
    height: '48%',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 8,
  },
  card: {
    width: 150,
    height: 150,
    backgroundColor: '#C0CFE4',
    position: 'absolute',
    marginTop: 280,
    marginLeft: 123,
    borderColor: '#DBDCE7',
    borderWidth: 5,
    elevation: 4,
    shadowColor: '#FFFFFF',
  },
  title: {
    textAlign: 'center',
    fontSize: 33,
    marginTop: 120,
    color: '#4D5975B7',
  },
  containerlinks: {
    flexDirection: 'row',
    height: '22%',
    width: '100%',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    elevation: 1,
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderColor: '#3E6DDB02',
    paddingBottom: 15,
  },

  bkg3: {
    flexDirection: 'row',
    height: '9%',
    width: '100%',
    justifyContent: 'space-around',
    alignItems: 'center',
  },

  bkgContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },

  btnText: {
    width: '33.33%',
    height: '100%',
    backgroundColor: '#EBEDF5',
    textAlign: 'center',
    fontSize: 21,
    fontWeight: 'bold',
    paddingTop: 20,
    paddingLeft: 5,
    paddingRight: 10,
    color: '#4D5975B7',
    elevation: 2,
  },
  text1: {
    fontSize: 15,
    color: '#4D5975B7',
    marginRight: 160,
  },
});
export default styles;
